{
  "hash": "9a66d6aa26762bb9048fbc7f045463ac",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Day 4: Survival Analysis\"\nsubtitle: \"Molecular Medicine - Oncology, Biostatistics\"\nauthor: \"Jeroen D. Mulder, Pär Villner, Karl Oskar Ekvall\"\ndate: now\n---\n\nIn these lab exercises you will gain experience with survival analysis in `R`. For this, you will use data from an animal experiment involving $n = 400$ rats. \n\n# Data Description\nThe $n = 400$ rats participated in an experiment, in which they had to find cheese in a labyrinth. The rats are randomly assigned to a variety of conditions:\n\n- `time_from_last_meal`: hours since the last meal (0-24)\n- `previous training`: how many times the rat did the same exercise in the past\n- `cheese`: the type of cheese (parmesan, gorgonzola, emmental, and feta)\n\nThe dataset includes various variables related to the outcome: \n\n- `avg_speed`\n- `find_cheese` (0 = no, 1 = yes)\n- `time_to_find` (censored if not found within 1 minute).\n\nNote that time *T* of interest is the time it takes to find the cheese, so when we speak of \"survival until time *t*\", we mean the event *T* > *t*.\n\nLoad the data into R using the `readRDS()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlab5_dat <- readRDS(\"./data/data5.Rds\")\nstr(lab5_dat) # Should show data.frame with 400 obs of 6 variables\n```\n:::\n\n\n# Survival Analysis\nTo perform survival analysis in R, we make use of the `survival` package, which can be installed with `install.packages(\"survival\")` and loaded with `library(survival)`. \n\n### Question 1\nUse the code below and look at the table presented. Explain what the survival column means, and do the calculations necessary to get the same numbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt <- c(2, 4, 5, 6, 8)\ns <- c(1, 0, 1, 0, 1)\n\nlibrary(survival)\nsurv_fit <- survfit(Surv(t, s) ~ 1)\n\nsummary(surv_fit)\n```\n:::\n\n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" icon=false title=\"Answer\"}\nThe first two lines create artifical surival data, where `t` represents the time at which an event happens, and `s` represents whether this event is censoring or the event of interest.\n\nThe line `surv_fit <- survfit(Surv(t, s) ~ 1)` does two things simultaneously. First, the function `Surv()` takes the data, and transforms it into an outcome variable that can be read by the `survfit()` function (which does the actual model fitting). Runnining `Surv(t, s)` shows that for the censored outcomes, a `+` sign is added to the survival time, indicating that the event is right censored. \n\nUsing this data, we can compute the survival probabilities manually: \n\n- Time 2: $\\frac{4}{5}$ survive, 4 persons remain after this time;  \n- Time 4: one person is censored. They leaves the dataset. Survival is still $\\frac{4}{5}$, but only 3 persons remain after this time.  \n- Time 5: person dies, so the survival probability is updated to $\\frac{2}{3} \\times \\frac{4}{5} = \\frac{8}{15} = 0.5333$.   \n- Time 6: one person is censored. They leaves the dataset. Survival probability remains the same, but only one person is left.  \n- Time 8: Last person dies. We observed no one who survived longer than 8, so we estimate the probability of surviving longer to be 0.\n:::\n\n### Question 2\n\nFit a simple logistic regression model investigating whether mice are more likely to find gorgonzola cheese than the other cheese types. Comment on the results. \n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" icon=false title=\"Answer\"}\nA logistic regression model can be fitted with the below code:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit logistic regression model\nfit_logistic <- glm(\n  formula = find_cheese ~ as.numeric(lab5_dat$cheese == \"gorgonzola\"),\n  data = lab5_dat,\n  family = binomial\n)\n\n# Inspect output\nsummary(fit_logistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = find_cheese ~ as.numeric(lab5_dat$cheese == \"gorgonzola\"), \n    family = binomial, data = lab5_dat)\n\nCoefficients:\n                                            Estimate Std. Error z value\n(Intercept)                                   0.4194     0.1180   3.553\nas.numeric(lab5_dat$cheese == \"gorgonzola\")   0.4760     0.2500   1.904\n                                            Pr(>|z|)    \n(Intercept)                                  0.00038 ***\nas.numeric(lab5_dat$cheese == \"gorgonzola\")  0.05690 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 527.16  on 399  degrees of freedom\nResidual deviance: 523.41  on 398  degrees of freedom\nAIC: 527.41\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(coef(fit_logistic)[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nas.numeric(lab5_dat$cheese == \"gorgonzola\") \n                                    1.60964 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Transform to probabilities\n1 / (1 + exp(-0.42 - 0.48))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7109495\n```\n\n\n:::\n\n```{.r .cell-code}\n1 / (1 + exp(-0.42))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6034832\n```\n\n\n:::\n:::\n\n\nThe result indicate that the odds ratio is $e^{0.4760} = 1.60964$, indicating that the odds of finding gorgonzola cheese are higher than for finding other cheese types. This effect, however, is not significant at the 0.05 level, and hence I would not put too much weight on it. \n\nTo transform these results on the probability scale, we can make use of the logistic function that was discussed in day 2. The probability of finding gorgonzola is estimated to be $1 / (1 + \\exp(-0.42 - 0.48)) =$ while the probability for the other cheese types is estimated to be $1 / (1 + \\exp(-0.42))$.\n:::\n\n### Question 3\n\nDefine a new variable called `long_training`. This variable divides the rats into those who have had more training than the median amount of experience with this exercise, and those who had less than the median. Interpret the Kaplan-Meier plot for both groups.\n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" icon=false title=\"Answer\"}\nYou can create the new variable with:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the new `long_training` variable\nlab5_dat$long_training <- lab5_dat$previous_training > median(lab5_dat$previous_training)\n```\n:::\n\nTo create the Kaplan-Meier survival curves for both groups, you can fit a survival model in which the survival time is predicted by group: \n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a survival model predicting to finding by training experience\nfit <- survfit(\n  Surv(time_to_find, find_cheese) ~ long_training,\n  data = lab5_dat\n)\n\n# Plot Kaplan-Meier curves per group (indicated by different line types, lty)\nplot(fit, lty = 1:2)\n\n# Add a legend to the plot\nlegend(\"bottomleft\", legend = c(\"short training\", \"long training\"), lty = 1:2)\n```\n\n::: {.cell-output-display}\n![](Biostatsweek_Lab5_ans_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe figure indicates that survival probabilities, that is, the probability of not finding the cheese, are larger for mice with short training. Survival probabilities appear to be decreasing approximately linearly in time.\n:::\n\n### Question 4\n\nPlot the survival function of the time it took all the mice to find cheese. When is the hazard rate the highest and the lowest?\n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" icon=false title=\"Answer\"}\nTo plot a survival function for all mice, we can use the same function, `survfit()`, but simply without any predictors (groups):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimate a survival curve across the entire sample\nfit <- survfit(Surv(time_to_find, find_cheese) ~ 1, data = lab5_dat)\n\n# Visualize estimated survival curve\nplot(fit, conf.int = F)\n```\n\n::: {.cell-output-display}\n![](Biostatsweek_Lab5_ans_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nTo estimate hazards, we need to run a Cox regression. Again, we do this without any predictors in the model such that the estimated hazard is representative for the entire sample: \n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a Cox proportional hazards model\nreg_fit <- coxph(\n  formula = Surv(time_to_find, find_cheese) ~ 1,\n  data = lab5_dat\n)\n\n# Estimate the baseline hazard\nbaseline <- basehaz(reg_fit)\n\n# Visualize the estimated hazard rate (i.e., combining estimates of Cox proportional hazard model and baseline hazard)\nplot(baseline$time, baseline$hazard, type = \"l\", main = \"Hazard rates\")\n```\n\n::: {.cell-output-display}\n![](Biostatsweek_Lab5_ans_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nIt looks like the mice are finding cheese uniformly over the time period. The hazard rate (i.e., the slope) is lowest (i.e., most horizontal) at the beginning and highest at the end.\n:::\n\n### Question 5\n\nPerform a log-rank test to see if mice with less than 5 hours of training have the same survival function as mice with 5 or more hours of training.\n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" icon=false title=\"Answer\"}\nFirst, create a new variable indicating whether mice had more or less than 5 hours of training: \n\n::: {.cell}\n\n```{.r .cell-code}\n# Create indicator for less than 5 hours of training\nlab5_dat$less_than_5 <- lab5_dat$previous_training < 5\n```\n:::\n\n\nSecond, run a log-rank test comparing both groups on their mean survival time (i.e., time until finding the cheese):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- survdiff(\n  formula = Surv(time_to_find, find_cheese) ~ less_than_5,\n  data = lab5_dat\n)\n\nprint(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(time_to_find, find_cheese) ~ less_than_5, \n    data = lab5_dat)\n\n                    N Observed Expected (O-E)^2/E (O-E)^2/V\nless_than_5=FALSE 218      171      118      23.3      45.1\nless_than_5=TRUE  182       81      134      20.7      45.1\n\n Chisq= 45.1  on 1 degrees of freedom, p= 2e-11 \n```\n\n\n:::\n:::\n\n\nWe reject the null hypothesis of identical survival functions because the p-value is below our (default) significance criterion of 0.05. \n:::\n\n### Question 6\n\nPlot the survival functions for each cheese type. Which cheeses to the mice find easiest to find? \n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" icon=false title=\"Answer\"}\n\nFit the survival curves again using `survfit()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a Kaplan-Meier model\nkm_plot <- survfit(Surv(time_to_find, find_cheese) ~ cheese, data = lab5_dat)\n\n# Plot the model-implied survival curves\nplot(km_plot, col = 1:4, lty = 1:4, xlab = \"Time\", ylab = \"Survival Probability\")\n\n# Add a legend identifying cheeses with different colors (col) and line types (lty)\nlegend(\"topright\", legend = levels(lab5_dat$cheese), col = 1:4, lty = 1:4, title = \"Groups\")\n```\n\n::: {.cell-output-display}\n![](Biostatsweek_Lab5_ans_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nGorgonzola and emmental seem to be the easiest cheeses to find (which, personally, I would avoid). \n:::\n\n### Question 7\n\nFit a Cox proportional hazards regression model with `time_to_find` as response and `cheese` as regressor. Do the results correspond with your answers in the previous question?\n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" icon=false title=\"Answer\"}\n\nA Cox proportional hazards model is fitted in R using `coxph()`: \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoxph(Surv(time_to_find, find_cheese) ~ cheese, data = lab5_dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time_to_find, find_cheese) ~ cheese, data = lab5_dat)\n\n                    coef exp(coef) se(coef)      z     p\ncheesefeta       -0.2030    0.8163   0.1815 -1.118 0.263\ncheesegorgonzola  0.2153    1.2402   0.1669  1.290 0.197\ncheeseparmesan   -0.1796    0.8356   0.1777 -1.011 0.312\n\nLikelihood ratio test=6.94  on 3 df, p=0.07373\nn= 400, number of events= 252 \n```\n\n\n:::\n:::\n\n\nYes, the estimates of the hazards correspond to what we saw in the plot. Gorgonzola has the highest hazard rate followed by emmentaler, meaning that mice found those cheeses at a higher rate, meaning they are found sooner as well. This also makes sense as survival probability and hazard rate are simply two different statistics/measures that represent the same thing!\n:::\n\n### Question 8\n\nFit a proportional hazards regression model with `time_to_find` as response and `time_from_last_meal`, `previous_training`, and `cheese` as predictors. Interpret the output.\n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" icon=false title=\"Answer\"}\n\nThe estimates indicate time from last meal, previous training, gorgonzola, and parmesan all increase the probability of finding the cheese within a certain time; that is, they increase the hazard. For example, one unit extra of previous training on average leads to, all else equal, a hazard which is increased by a factor of $\\exp(0.19) \\approx 1.2$. The p-values indicate time from last meal, previous training, and cheese type (on the 10% level) are important predictors in this model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoxph(Surv(time_to_find, find_cheese) ~ time_from_last_meal + previous_training + cheese, data = lab5_dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time_to_find, find_cheese) ~ time_from_last_meal + \n    previous_training + cheese, data = lab5_dat)\n\n                        coef exp(coef) se(coef)      z      p\ntime_from_last_meal  0.11184   1.11833  0.01038 10.773 <2e-16\nprevious_training    0.19331   1.21326  0.02178  8.875 <2e-16\ncheesefeta          -0.06015   0.94162  0.18200 -0.330 0.7410\ncheesegorgonzola     0.33648   1.40001  0.16797  2.003 0.0452\ncheeseparmesan       0.06964   1.07213  0.17893  0.389 0.6971\n\nLikelihood ratio test=188.2  on 5 df, p=< 2.2e-16\nn= 400, number of events= 252 \n```\n\n\n:::\n:::\n\n:::\n\n### Question 9\n\nDoes it seem like the proportional hazards assumption is fulfilled for the model in question 8?\n\n::: {.callout-note appearance=\"simple\" collapse=\"true\" icon=false title=\"Answer\"}\n\nWe can test teh proportional hazards assumption using Schoenfeld residuals. In `R`, we can test if these residuals are independent of time with the `cox.zph()` function. To this end, first fit the Cox model, and then call the `cox.zph()` function on this object: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the Cox models\nfit1 <- coxph(\n  formula = Surv(time_to_find, find_cheese) ~ time_from_last_meal + previous_training + cheese,\n  data = lab5_dat\n)\n\nfit2 <- coxph(\n  formula = Surv(time_to_find, find_cheese) ~ previous_training < 5,\n  data = lab5_dat\n)\n\n# Test if the Schoenfeld residuals (computed from the model) are independent of time\ncox.zph(fit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     chisq df       p\ntime_from_last_meal 15.503  1 8.2e-05\nprevious_training    6.204  1  0.0127\ncheese               0.354  3  0.9496\nGLOBAL              19.912  5  0.0013\n```\n\n\n:::\n\n```{.r .cell-code}\ncox.zph(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      chisq df     p\nprevious_training < 5  3.82  1 0.051\nGLOBAL                 3.82  1 0.051\n```\n\n\n:::\n:::\n\n\nThe null hypothesis is that there is a proportional relationship between the hazards. We see that the p-value is 0.051 so on the 0.05 significance level we would not reject.\n:::\n",
    "supporting": [
      "Biostatsweek_Lab5_ans_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}